merge_queue:
  queue_controls_comment: false

queue_rules:
  - name: default
    queue_conditions:
      - check-success ~= "^Build and Test.*$"

pull_request_rules:
  - name: queue PRs marked for merge after build success
    conditions:
      - label = merge-on-build-success
    actions:
      queue:
        name: default

  - name: auto-merge Scala Steward PRs after build success
    conditions:
      - author = scala-steward
      - check-success ~= "^Build and Test.*$"
    actions:
      queue:
        name: default
