merge_queue:
  queue_controls_comment: false

queue_rules:
  - name: default
    merge_conditions:
      - check-success ~= ^Build and Test.*$

pull_request_rules:
  - name: queue PRs marked for merge
    conditions:
      - label = merge-on-build-success
    actions:
      queue:
        name: default

  - name: auto-queue Scala Steward PRs
    conditions:
      - author = scala-steward
    actions:
      queue:
        name: default
