merge_queue:
  queue_controls_comment: false

queue_rules:
  - name: default
    queue_conditions:
      - check-success = @github-actions/Build and Test (ubuntu-latest, all, temurin@17)

pull_request_rules:
  - name: queue PRs marked for merge after build success
    conditions:
      - label = merge-on-build-success
    actions:
      queue:
        name: default

  - name: auto-merge Scala Steward PRs after build success
    conditions:
      - author = scala-steward
      - check-success = @github-actions/Build and Test (ubuntu-latest, all, temurin@17)
    actions:
      queue:
        name: default
