version="3.11.2"
maxColumn = 120
trailingCommas = always
continuationIndent.defnSite = 2

align.preset = some
align.tokens = []
rewrite.redundantBraces.stringInterpolation = true
runner.dialect = scala3
