{
  lazy val derivedDiffer$macro$3: difflicious.Differ[difflicious.testtypes.TreeContainer] = ((new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeContainer](((new difflicious.differ.ProductDiffer[difflicious.testtypes.TreeContainer](Vector.empty[(String, difflicious.Differ[Any])].:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("c1", derivedDiffer$macro$4.asInstanceOf[difflicious.Differ[Any]])).:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("c2", derivedDiffer$macro$6.asInstanceOf[difflicious.Differ[Any]])).:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("option", derivedDiffer$macro$8.asInstanceOf[difflicious.Differ[Any]])).:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("either", derivedDiffer$macro$9.asInstanceOf[difflicious.Differ[Any]])).:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("map", derivedDiffer$macro$10.asInstanceOf[difflicious.Differ[Any]])).:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("list", derivedDiffer$macro$11.asInstanceOf[difflicious.Differ[Any]])), false, difflicious.utils.TypeName.apply[Any]("difflicious.testtypes.TreeContainer", "TreeContainer", Nil))): difflicious.Differ[difflicious.testtypes.TreeContainer]))): difflicious.Differ[difflicious.testtypes.TreeContainer]);
  lazy val derivedDiffer$macro$4: difflicious.Differ[difflicious.testtypes.TreeCaseClass1] = d1;
  lazy val derivedDiffer$macro$6: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = ((new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeCaseClass2](((new difflicious.differ.ProductDiffer[difflicious.testtypes.TreeCaseClass2](Vector.empty[(String, difflicious.Differ[Any])].:+[(String, difflicious.Differ[Any])](Tuple2.apply[String, difflicious.Differ[Any]]("value", derivedDiffer$macro$7.asInstanceOf[difflicious.Differ[Any]])), false, difflicious.utils.TypeName.apply[Any]("difflicious.testtypes.TreeCaseClass2", "TreeCaseClass2", Nil))): difflicious.Differ[difflicious.testtypes.TreeCaseClass2]))): difflicious.Differ[difflicious.testtypes.TreeCaseClass2]);
  lazy val derivedDiffer$macro$7: difflicious.Differ[String] = difflicious.Differ.stringDiffer;
  lazy val derivedDiffer$macro$8: difflicious.Differ[Option[difflicious.testtypes.TreeCaseClass2]] = difflicious.Differ.optionDiffer[difflicious.testtypes.TreeCaseClass2](derivedDiffer$macro$6).asInstanceOf[difflicious.Differ[Option[difflicious.testtypes.TreeCaseClass2]]];
  lazy val derivedDiffer$macro$9: difflicious.Differ[Either[difflicious.testtypes.TreeCaseClass1,difflicious.testtypes.TreeCaseClass2]] = difflicious.Differ.eitherDiffer[difflicious.testtypes.TreeCaseClass1, difflicious.testtypes.TreeCaseClass2](derivedDiffer$macro$4, derivedDiffer$macro$6).asInstanceOf[difflicious.Differ[Either[difflicious.testtypes.TreeCaseClass1,difflicious.testtypes.TreeCaseClass2]]];
  lazy val derivedDiffer$macro$10: difflicious.Differ[Map[String,difflicious.testtypes.TreeCaseClass2]] = new difflicious.differ.MapDiffer[Map, String, difflicious.testtypes.TreeCaseClass2](false, difflicious.Differ.stringDiffer, derivedDiffer$macro$6, difflicious.utils.TypeName.apply[Any]("Map", "Map", Nil), difflicious.utils.MapLike.stdMapAsMap[[K, +V]Map[K,V]]).asInstanceOf[difflicious.Differ[Map[String,difflicious.testtypes.TreeCaseClass2]]];
  lazy val derivedDiffer$macro$11: difflicious.Differ[List[Option[difflicious.testtypes.TreeCaseClass2]]] = difflicious.differ.SeqDiffer.create[List, Option[difflicious.testtypes.TreeCaseClass2]](derivedDiffer$macro$8, difflicious.utils.TypeName.apply[Any]("List", "List", Nil), difflicious.utils.SeqLike.stdSeqAsSeq[[+A]List[A]]).asInstanceOf[difflicious.Differ[List[Option[difflicious.testtypes.TreeCaseClass2]]]];
  derivedDiffer$macro$3
}
