{
  lazy val derivedDiffer$macro$2: difflicious.Differ[difflicious.testtypes.TreeContainer] = new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeContainer](new difflicious.differ.RecordDiffer[difflicious.testtypes.TreeContainer](ListMap.empty[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]].+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("c1", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(0)), d1.asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("c2", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(1)), derivedDiffer$macro$3.asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("option", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(2)), ({
  implicit val valueDiffer: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = derivedDiffer$macro$3;
  difflicious.Differ.optionDiffer[difflicious.testtypes.TreeCaseClass2](valueDiffer)
}).asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("either", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(3)), ({
  implicit val leftValueDiffer: difflicious.Differ[difflicious.testtypes.TreeCaseClass1] = d1;
  implicit val rightValueDiffer: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = derivedDiffer$macro$3;
  difflicious.Differ.eitherDiffer[difflicious.testtypes.TreeCaseClass1, difflicious.testtypes.TreeCaseClass2](leftValueDiffer, rightValueDiffer)
}).asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("map", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(4)), new difflicious.differ.MapDiffer[Map,String,difflicious.testtypes.TreeCaseClass2](false, difflicious.Differ.stringDiffer, derivedDiffer$macro$3, difflicious.utils.TypeName.apply[Map[String,difflicious.testtypes.TreeCaseClass2]](/*irrelevant*/), difflicious.utils.MapLike.stdMapAsMap[[K, +V]Map[K,V]]).asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]]]("list", Tuple2.apply[Function1[difflicious.testtypes.TreeContainer, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeContainer) => value.asInstanceOf[Product].productElement(5)), new difflicious.differ.SeqDiffer[List,Option[difflicious.testtypes.TreeCaseClass2]](false, difflicious.ConfigureOp.PairBy.Index, {
  implicit val valueDiffer: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = derivedDiffer$macro$3;
  difflicious.Differ.optionDiffer[difflicious.testtypes.TreeCaseClass2](valueDiffer)
}, difflicious.utils.TypeName.apply[List[Option[difflicious.testtypes.TreeCaseClass2]]](/*irrelevant*/), difflicious.utils.SeqLike.stdSeqAsSeq[[+A]List[A]]).asInstanceOf[difflicious.Differ[Any]]))), false, difflicious.utils.TypeName.apply[Any]("difflicious.testtypes.TreeContainer", "TreeContainer", Nil)));
  lazy val derivedDiffer$macro$3: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeCaseClass2](new difflicious.differ.RecordDiffer[difflicious.testtypes.TreeCaseClass2](ListMap.empty[String, Tuple2[Function1[difflicious.testtypes.TreeCaseClass2, Any], difflicious.Differ[Any]]].+[Tuple2[Function1[difflicious.testtypes.TreeCaseClass2, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.TreeCaseClass2, Any], difflicious.Differ[Any]]]("value", Tuple2.apply[Function1[difflicious.testtypes.TreeCaseClass2, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.TreeCaseClass2) => value.asInstanceOf[Product].productElement(0)), difflicious.Differ.stringDiffer.asInstanceOf[difflicious.Differ[Any]]))), false, difflicious.utils.TypeName.apply[Any]("difflicious.testtypes.TreeCaseClass2", "TreeCaseClass2", Nil)));
  derivedDiffer$macro$2
}
