{
  val DifferGen_this: difflicious.Differ.type = difflicious.Differ

  ({
    lazy val derivedDiffer$macro$3: difflicious.Differ[difflicious.testtypes.TreeContainer] = (new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeContainer]((new difflicious.differ.ProductDiffer[difflicious.testtypes.TreeContainer](scala.Vector.empty[Tuple2[String, difflicious.Differ[Any]]].:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("c1", derivedDiffer$macro$4.asInstanceOf[difflicious.Differ[Any]])).:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("c2", derivedDiffer$macro$6.asInstanceOf[difflicious.Differ[Any]])).:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("option", derivedDiffer$macro$8.asInstanceOf[difflicious.Differ[Any]])).:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("either", derivedDiffer$macro$9.asInstanceOf[difflicious.Differ[Any]])).:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("map", derivedDiffer$macro$10.asInstanceOf[difflicious.Differ[Any]])).:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("list", derivedDiffer$macro$11.asInstanceOf[difflicious.Differ[Any]])), false, difflicious.utils.TypeName.apply[Any](long = "difflicious.testtypes.TreeContainer", short = "TreeContainer", typeArguments = Nil)): difflicious.Differ[difflicious.testtypes.TreeContainer])): difflicious.Differ[difflicious.testtypes.TreeContainer])
    lazy val derivedDiffer$macro$4: difflicious.Differ[difflicious.testtypes.TreeCaseClass1] = d1
    lazy val derivedDiffer$macro$6: difflicious.Differ[difflicious.testtypes.TreeCaseClass2] = (new difflicious.differ.LazyDiffer[difflicious.testtypes.TreeCaseClass2]((new difflicious.differ.ProductDiffer[difflicious.testtypes.TreeCaseClass2](scala.Vector.empty[Tuple2[String, difflicious.Differ[Any]]].:+[Tuple2[String, difflicious.Differ[Any]]](Tuple2.apply[String, difflicious.Differ[Any]]("value", derivedDiffer$macro$7.asInstanceOf[difflicious.Differ[Any]])), false, difflicious.utils.TypeName.apply[Any](long = "difflicious.testtypes.TreeCaseClass2", short = "TreeCaseClass2", typeArguments = Nil)): difflicious.Differ[difflicious.testtypes.TreeCaseClass2])): difflicious.Differ[difflicious.testtypes.TreeCaseClass2])
    lazy val derivedDiffer$macro$7: difflicious.Differ[String] = difflicious.Differ.stringDiffer
    lazy val derivedDiffer$macro$8: difflicious.Differ[Option[difflicious.testtypes.TreeCaseClass2]] = difflicious.Differ.optionDiffer[difflicious.testtypes.TreeCaseClass2](derivedDiffer$macro$6).asInstanceOf[difflicious.Differ[Option[difflicious.testtypes.TreeCaseClass2]]]
    lazy val derivedDiffer$macro$9: difflicious.Differ[Either[difflicious.testtypes.TreeCaseClass1, difflicious.testtypes.TreeCaseClass2]] = difflicious.Differ.eitherDiffer[difflicious.testtypes.TreeCaseClass1, difflicious.testtypes.TreeCaseClass2](derivedDiffer$macro$4, derivedDiffer$macro$6).asInstanceOf[difflicious.Differ[Either[difflicious.testtypes.TreeCaseClass1, difflicious.testtypes.TreeCaseClass2]]]
    lazy val derivedDiffer$macro$10: difflicious.Differ[Map[String, difflicious.testtypes.TreeCaseClass2]] = new difflicious.differ.MapDiffer[[K >: Nothing <: Any, V >: Nothing <: Any] =>> Map[K, V], String, difflicious.testtypes.TreeCaseClass2](false, difflicious.Differ.stringDiffer, derivedDiffer$macro$6, difflicious.utils.TypeName.apply[Any](long = "Map", short = "Map", typeArguments = Nil), difflicious.utils.MapLike.stdMapAsMap[[K >: Nothing <: Any, V >: Nothing <: Any] =>> Map[K, V]])
    lazy val derivedDiffer$macro$11: difflicious.Differ[List[Option[difflicious.testtypes.TreeCaseClass2]]] = differ.SeqDiffer.create[[A >: Nothing <: Any] =>> List[A], Option[difflicious.testtypes.TreeCaseClass2]](derivedDiffer$macro$8, difflicious.utils.TypeName.apply[Any](long = "List", short = "List", typeArguments = Nil), difflicious.utils.SeqLike.stdSeqAsSeq[[A >: Nothing <: Any] =>> List[A]])

    (derivedDiffer$macro$3: difflicious.Differ[difflicious.testtypes.TreeContainer])
  }: difflicious.Differ[difflicious.testtypes.TreeContainer])
}
