{
  val DifferGen_this: difflicious.Differ.type = difflicious.Differ

  ({
    lazy val derivedDiffer$macro$5: difflicious.Differ[difflicious.testtypes.RecursiveDerivedDeepNode] = new difflicious.differ.LazyDiffer[difflicious.testtypes.RecursiveDerivedDeepNode](new difflicious.differ.RecordDiffer[difflicious.testtypes.RecursiveDerivedDeepNode](fieldDiffers = ListMap.empty[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]]].+[Tuple2[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]]]("value", Tuple2.apply[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.RecursiveDerivedDeepNode) => value.asInstanceOf[Product].productElement(0)), difflicious.Differ.stringDiffer.asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]]]("children", Tuple2.apply[Function1[difflicious.testtypes.RecursiveDerivedDeepNode, Any], difflicious.Differ[Any]](((`value₂`: difflicious.testtypes.RecursiveDerivedDeepNode) => `value₂`.asInstanceOf[Product].productElement(1)), new difflicious.differ.SeqDiffer[List, difflicious.testtypes.RecursiveDerivedDeepNode][[A >: Nothing <: Any] =>> List[A], difflicious.testtypes.RecursiveDerivedDeepNode](false, difflicious.ConfigureOp.PairBy.Index, derivedDiffer$macro$5, difflicious.utils.TypeName.apply[List[difflicious.testtypes.RecursiveDerivedDeepNode]](/*irrelevant*/), difflicious.utils.SeqLike.stdSeqAsSeq[[A >: Nothing <: Any] =>> List[A]]).asInstanceOf[difflicious.Differ[Any]]))), isIgnored = false, typeName = difflicious.utils.TypeName.apply[Any](long = "difflicious.testtypes.RecursiveDerivedDeepNode", short = "RecursiveDerivedDeepNode", typeArguments = Nil)))

    (derivedDiffer$macro$5: difflicious.Differ[difflicious.testtypes.RecursiveDerivedDeepNode])
  }: difflicious.Differ[difflicious.testtypes.RecursiveDerivedDeepNode])
}
