{
  val DifferGen_this: difflicious.Differ.type = difflicious.Differ

  ({
    lazy val derivedDiffer$macro$4: difflicious.Differ[difflicious.testtypes.RecursiveDerivedNode] = new difflicious.differ.LazyDiffer[difflicious.testtypes.RecursiveDerivedNode](new difflicious.differ.RecordDiffer[difflicious.testtypes.RecursiveDerivedNode](fieldDiffers = ListMap.empty[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]]].+[Tuple2[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]]]("value", Tuple2.apply[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]](((value: difflicious.testtypes.RecursiveDerivedNode) => value.asInstanceOf[Product].productElement(0)), difflicious.Differ.stringDiffer.asInstanceOf[difflicious.Differ[Any]]))).+[Tuple2[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]]](Tuple2.apply[String, Tuple2[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]]]("children", Tuple2.apply[Function1[difflicious.testtypes.RecursiveDerivedNode, Any], difflicious.Differ[Any]](((`value₂`: difflicious.testtypes.RecursiveDerivedNode) => `value₂`.asInstanceOf[Product].productElement(1)), new difflicious.differ.SeqDiffer[List, difflicious.testtypes.RecursiveDerivedNode][[A >: Nothing <: Any] =>> List[A], difflicious.testtypes.RecursiveDerivedNode](false, difflicious.ConfigureOp.PairBy.Index, derivedDiffer$macro$4, difflicious.utils.TypeName.apply[List[difflicious.testtypes.RecursiveDerivedNode]](/*irrelevant*/), difflicious.utils.SeqLike.stdSeqAsSeq[[A >: Nothing <: Any] =>> List[A]]).asInstanceOf[difflicious.Differ[Any]]))), isIgnored = false, typeName = difflicious.utils.TypeName.apply[Any](long = "difflicious.testtypes.RecursiveDerivedNode", short = "RecursiveDerivedNode", typeArguments = Nil)))

    (derivedDiffer$macro$4: difflicious.Differ[difflicious.testtypes.RecursiveDerivedNode])
  }: difflicious.Differ[difflicious.testtypes.RecursiveDerivedNode])
}
